Fix TypeError: "self.emit is not a function"
The error was due to calling self.emit("error", err); instead of self.db.emit("error", err).
There may be other error when calling self.emit("detach", false) in index.